### PR TITLE
feat(webseal): allow to prefill fields using query params

### PR DESCRIPTION
**Pull request by cberthou**

### CODE REVIEW

**Comment by revolunet** [comment]
I dont think we should encourage to pass secrets through url query ?

this data would be logged in http servers, routers and browser

**Comment by cberthou** [comment]
Secrets cannot be prefilled. Only `["namespace", "scope", "cluster", "name"]` can be prefilled.

**Comment by revolunet** [comment]
awesome thanks !

**Comment by revolunet** [comment]
ha. looks like renovate broke all the things

**Comment by revolunet** [comment]
replaced by #48, thanks !

**Pull request closed without merging**
